# Generated by Django 4.0.1 on 2022-01-17 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_post_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='post',
            name='clip',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='yu', upload_to='post_images'),
            preserve_default=False,
        ),
    ]
