# Generated by Django 4.0.1 on 2022-01-17 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_alter_post_clip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='clip',
            new_name='image',
        ),
    ]
