# Generated by Django 4.0.1 on 2022-01-17 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_rename_clip_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(upload_to='post_images'),
        ),
    ]
