# Generated by Django 4.0.1 on 2022-01-17 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_alter_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='clip',
            field=models.FileField(default='ui', upload_to=''),
            preserve_default=False,
        ),
    ]
