# Generated by Django 4.0.1 on 2022-01-17 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_remove_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
