# Generated by Django 4.0.1 on 2022-01-17 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0015_remove_post_content_remove_post_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Clip',
        ),
    ]
